-
  branches:
    only:
      - master
  environment:
    nodejs_version: "6"
    NPM_TOKEN:
      secure: CF0+NkSX0D4jrSH20ybWD6TXIiYK0X19r02p1u0NqZORVoCBVhmOCRVjc93Bd4DW

  before_build:
    - npm install

  build_script:
    - npm run build
    - npm run test
    - echo publish package
    - npm run ci-publish
-
  branches:
    only:
      - dev
  environment:
    nodejs_version: "6"

  before_build:
    - npm install

  build_script:
    - npm run build
    - npm run test